In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [5]:
user_data = pd.read_csv('../../data/Week1_challenge_data_source(CSV).csv')
user_data

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,1.585461e+07,2.501332e+06,8.198936e+06,9.656251e+06,2.780823e+08,1.434415e+07,1.717444e+08,8.814393e+06,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,2.024740e+07,1.911173e+07,1.833841e+07,1.722713e+07,6.087501e+08,1.170709e+06,5.269042e+08,1.505514e+07,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,1.972566e+07,1.469958e+07,1.758779e+07,6.163408e+06,2.295846e+08,3.956300e+05,4.106926e+08,4.215763e+06,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,2.138812e+07,1.514664e+07,1.399465e+07,1.097942e+06,7.995382e+08,1.084972e+07,7.490399e+08,1.279728e+07,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,1.525938e+07,1.896287e+07,1.712458e+07,4.152180e+05,5.277072e+08,3.529801e+06,5.507095e+08,1.391032e+07,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,7.277826e+18,4/29/2019 7:28,451.0,4/30/2019 6:02,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,1.619167e+07,1.176343e+07,1.788370e+07,1.967816e+07,5.266097e+08,9.197207e+06,3.264510e+06,1.348742e+07,57628851.0,574175259.0
149997,7.349883e+18,4/29/2019 7:28,483.0,4/30/2019 10:41,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,1.387723e+07,8.288284e+06,1.935015e+07,2.129315e+07,6.268931e+08,4.735033e+06,7.121804e+08,2.457758e+06,39135081.0,666648844.0
149998,1.311448e+19,4/29/2019 7:28,283.0,4/30/2019 10:46,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,2.266051e+07,1.855903e+06,9.963942e+06,5.065760e+06,5.535395e+08,1.339432e+07,1.211009e+08,1.131473e+07,34912224.0,592786405.0
149999,1.311448e+19,4/29/2019 7:28,696.0,4/30/2019 10:40,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8.817106e+06,8.305402e+06,3.322253e+06,1.317259e+07,3.525370e+08,2.529475e+06,8.147131e+08,1.406930e+06,29626096.0,371895920.0
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,NaN,NaN

In [6]:
user_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

In [7]:
user_data.columns = ['Bearer_Id','Start', 'Start_ms', 'End', 'End_ms', 'Dur_ms', 'IMSI', 'MSISDN_Number', 'IMEI',
                    'Last_Location_Name', 'Avg_RTT_DL_(ms)', 'Avg_RTT_UL_(ms)', 'Avg_Bearer_TP_DL_(kbps)','Avg_Bearer_TP_UL_(kbps)',
                     'TCP_DL_Retrans_Vol_(Bytes)', 'TCP_UL_Retrans_Vol_(Bytes)', 'DL_TP_<_50_Kbps_(%)',
                     '50_Kbps_<_DL_TP_<_250_Kbps_(%)', '250_Kbps_<_DL_TP_<_1_Mbps_(%)', 'DL_TP_>_1_Mbps_(%)',
                     'UL_TP_<_10_Kbps_(%)', '10_Kbps_<_UL_TP_<_50_Kbps_(%)', '50_Kbps_<_UL_TP_<_300_Kbps_(%)',
                     'UL_TP_>_300_Kbps_(%)', 'HTTP_DL_(Bytes)', 'HTTP_UL_(Bytes)', 'Activity_Duration_DL_(ms)',
                     'Activity_Duration_UL_(ms)', 'Dur_(ms)_1', 'Handset_Manufacturer', 'Handset_Type',
                     'Nb_of_sec_with_125000B_<_Vol_DL', 'Nb_of_sec_with_1250B_<_Vol_UL_<_6250B', 'Nb_of_sec_with_31250B_<_Vol_DL_<_125000B',
                     'Nb_of_sec_with_37500B_<_Vol UL', 'Nb_of_sec_with_6250B_<_Vol_DL_<_31250B', 
                     'Nb_of_sec_with_6250B_<_Vol_UL_<_37500B', 'Nb_of_sec_with_Vol_DL_<_6250B', 
                    'Nb_of_sec_with_Vol_UL_<_1250B', 'Social_Media_DL_(Bytes)', 'Social_Media_UL_(Bytes)',
                     'Google_DL_(Bytes)', 'Google_UL_(Bytes)', 'Email_DL(Bytes)', 'Email_UL(Bytes)', 
                     'Youtube_DL_(Bytes)', 'Youtube_UL_(Bytes)', 'Netflix_DL_(Bytes)', 'Netflix_UL_(Bytes)',
                     'Gaming_DL_(Bytes)', 'Gaming_UL_(Bytes)', 'Other_DL_(Bytes)', 'Other_UL_(Bytes)',
                     'Total_UL_(Bytes)','Total_DL_(Bytes)'
                    ]

In [8]:
#Determining the number of data points
print(f" There are {user_data.shape[0]} rows and {user_data.shape[1]} columns")

 There are 150001 rows and 55 columns

In [9]:
#Checking whether there are errors in the data
print("The number of missing value(s): {}".format(user_data.isnull().sum().sum()))
print("Columns having missing columns value:{}".format(user_data.columns[user_data.isnull().any()]))

The number of missing value(s): 1031392
Columns having missing columns value:Index(['Bearer_Id', 'Start', 'Start_ms', 'End', 'End_ms', 'Dur_ms', 'IMSI',
       'MSISDN_Number', 'IMEI', 'Last_Location_Name', 'Avg_RTT_DL_(ms)',
       'Avg_RTT_UL_(ms)', 'Avg_Bearer_TP_DL_(kbps)', 'Avg_Bearer_TP_UL_(kbps)',
       'TCP_DL_Retrans_Vol_(Bytes)', 'TCP_UL_Retrans_Vol_(Bytes)',
       'DL_TP_<_50_Kbps_(%)', '50_Kbps_<_DL_TP_<_250_Kbps_(%)',
       '250_Kbps_<_DL_TP_<_1_Mbps_(%)', 'DL_TP_>_1_Mbps_(%)',
       'UL_TP_<_10_Kbps_(%)', '10_Kbps_<_UL_TP_<_50_Kbps_(%)',
       '50_Kbps_<_UL_TP_<_300_Kbps_(%)', 'UL_TP_>_300_Kbps_(%)',
       'HTTP_DL_(Bytes)', 'HTTP_UL_(Bytes)', 'Activity_Duration_DL_(ms)',
       'Activity_Duration_UL_(ms)', 'Dur_(ms)_1', 'Handset_Manufacturer',
       'Handset_Type', 'Nb_of_sec_with_125000B_<_Vol_DL',
       'Nb_of_sec_with_1250B_<_Vol_UL_<_6250B',
       'Nb_of_sec_with_31250B_<_Vol_DL_<_125000B',
       'Nb_of_sec_with_37500B_<_Vol UL',
       'Nb_of_sec_with_6250B_<_Vol_DL_<_31250B',
       'Nb_of_sec_with_6250B_<_Vol_UL_<_37500B',
       'Nb_of_sec_with_Vol_DL_<_6250B', 'Nb_of_sec_with_Vol_UL_<_1250B',
       'Total_UL_(Bytes)', 'Total_DL_(Bytes)'],
      dtype='object')

In [10]:
#Filling the cells having null value with the mean of their respective columns
user_data.fillna(user_data.mean().round(1), inplace=True)

In [11]:
print("The number of missing value(s): {}".format(user_data.isnull().sum().sum()))
print("Columns having missing columns value:{}".format(user_data.columns[user_data.isnull().any()]))

The number of missing value(s): 2299
Columns having missing columns value:Index(['Start', 'End', 'Last_Location_Name', 'Handset_Manufacturer',
       'Handset_Type'],
      dtype='object')

In [12]:
#Checking for columns with null values
user_data.isna().sum()

Bearer_Id                                      0
Start                                          1
Start_ms                                       0
End                                            1
End_ms                                         0
Dur_ms                                         0
IMSI                                           0
MSISDN_Number                                  0
IMEI                                           0
Last_Location_Name                          1153
Avg_RTT_DL_(ms)                                0
Avg_RTT_UL_(ms)                                0
Avg_Bearer_TP_DL_(kbps)                        0
Avg_Bearer_TP_UL_(kbps)                        0
TCP_DL_Retrans_Vol_(Bytes)                     0
TCP_UL_Retrans_Vol_(Bytes)                     0
DL_TP_<_50_Kbps_(%)                            0
50_Kbps_<_DL_TP_<_250_Kbps_(%)                 0
250_Kbps_<_DL_TP_<_1_Mbps_(%)                  0
DL_TP_>_1_Mbps_(%)                             0
UL_TP_<_10_Kbps_(%)                            0
10_Kbps_<_UL_TP_<_50_Kbps_(%)                  0
50_Kbps_<_UL_TP_<_300_Kbps_(%)                 0
UL_TP_>_300_Kbps_(%)                           0
HTTP_DL_(Bytes)                                0
HTTP_UL_(Bytes)                                0
Activity_Duration_DL_(ms)                      0
Activity_Duration_UL_(ms)                      0
Dur_(ms)_1                                     0
Handset_Manufacturer                         572
Handset_Type                                 572
Nb_of_sec_with_125000B_<_Vol_DL                0
Nb_of_sec_with_1250B_<_Vol_UL_<_6250B          0
Nb_of_sec_with_31250B_<_Vol_DL_<_125000B       0
Nb_of_sec_with_37500B_<_Vol UL                 0
Nb_of_sec_with_6250B_<_Vol_DL_<_31250B         0
Nb_of_sec_with_6250B_<_Vol_UL_<_37500B         0
Nb_of_sec_with_Vol_DL_<_6250B                  0
Nb_of_sec_with_Vol_UL_<_1250B                  0
Social_Media_DL_(Bytes)                        0
Social_Media_UL_(Bytes)                        0
Google_DL_(Bytes)                              0
Google_UL_(Bytes)                              0
Email_DL(Bytes)                                0
Email_UL(Bytes)                                0
Youtube_DL_(Bytes)                             0
Youtube_UL_(Bytes)                             0
Netflix_DL_(Bytes)                             0
Netflix_UL_(Bytes)                             0
Gaming_DL_(Bytes)                              0
Gaming_UL_(Bytes)                              0
Other_DL_(Bytes)                               0
Other_UL_(Bytes)                               0
Total_UL_(Bytes)                               0
Total_DL_(Bytes)                               0
dtype: int64

In [13]:
'''Fill the null values of the remaining columns with the respective column mode'''
for i in ['Start', 'End', 'Last_Location_Name', 'Handset_Manufacturer', 'Handset_Type']:
    user_data[i] = user_data[i].fillna(user_data[i].mode()[0])

In [14]:
print("The number of missing value(s): {}".format(user_data.isnull().sum().sum()))
print("Columns having missing columns value:{}".format(user_data.columns[user_data.isnull().any()]))

The number of missing value(s): 0
Columns having missing columns value:Index([], dtype='object')

In [15]:
user_data.isna().sum()

Bearer_Id                                   0
Start                                       0
Start_ms                                    0
End                                         0
End_ms                                      0
Dur_ms                                      0
IMSI                                        0
MSISDN_Number                               0
IMEI                                        0
Last_Location_Name                          0
Avg_RTT_DL_(ms)                             0
Avg_RTT_UL_(ms)                             0
Avg_Bearer_TP_DL_(kbps)                     0
Avg_Bearer_TP_UL_(kbps)                     0
TCP_DL_Retrans_Vol_(Bytes)                  0
TCP_UL_Retrans_Vol_(Bytes)                  0
DL_TP_<_50_Kbps_(%)                         0
50_Kbps_<_DL_TP_<_250_Kbps_(%)              0
250_Kbps_<_DL_TP_<_1_Mbps_(%)               0
DL_TP_>_1_Mbps_(%)                          0
UL_TP_<_10_Kbps_(%)                         0
10_Kbps_<_UL_TP_<_50_Kbps_(%)               0
50_Kbps_<_UL_TP_<_300_Kbps_(%)              0
UL_TP_>_300_Kbps_(%)                        0
HTTP_DL_(Bytes)                             0
HTTP_UL_(Bytes)                             0
Activity_Duration_DL_(ms)                   0
Activity_Duration_UL_(ms)                   0
Dur_(ms)_1                                  0
Handset_Manufacturer                        0
Handset_Type                                0
Nb_of_sec_with_125000B_<_Vol_DL             0
Nb_of_sec_with_1250B_<_Vol_UL_<_6250B       0
Nb_of_sec_with_31250B_<_Vol_DL_<_125000B    0
Nb_of_sec_with_37500B_<_Vol UL              0
Nb_of_sec_with_6250B_<_Vol_DL_<_31250B      0
Nb_of_sec_with_6250B_<_Vol_UL_<_37500B      0
Nb_of_sec_with_Vol_DL_<_6250B               0
Nb_of_sec_with_Vol_UL_<_1250B               0
Social_Media_DL_(Bytes)                     0
Social_Media_UL_(Bytes)                     0
Google_DL_(Bytes)                           0
Google_UL_(Bytes)                           0
Email_DL(Bytes)                             0
Email_UL(Bytes)                             0
Youtube_DL_(Bytes)                          0
Youtube_UL_(Bytes)                          0
Netflix_DL_(Bytes)                          0
Netflix_UL_(Bytes)                          0
Gaming_DL_(Bytes)                           0
Gaming_UL_(Bytes)                           0
Other_DL_(Bytes)                            0
Other_UL_(Bytes)                            0
Total_UL_(Bytes)                            0
Total_DL_(Bytes)                            0
dtype: int64

In [16]:
user_data.head()

,Bearer_Id,Start,Start_ms,End,End_ms,Dur_ms,IMSI,MSISDN_Number,IMEI,Last_Location_Name,...,Youtube_DL_(Bytes),Youtube_UL_(Bytes),Netflix_DL_(Bytes),Netflix_UL_(Bytes),Gaming_DL_(Bytes),Gaming_UL_(Bytes),Other_DL_(Bytes),Other_UL_(Bytes),Total_UL_(Bytes),Total_DL_(Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [17]:
plot_count(user_data, 'Handset_Type')

NameError: name 'plot_count' is not defined

In [18]:
#Determining the frequency of the top 10 Handset types used in the data
handset_frequency = user_data['Handset_Type'].value_counts()
handset_frequency[0:10]

Huawei B528S-23A                20324
Apple iPhone 6S (A1688)          9419
Apple iPhone 6 (A1586)           9023
undefined                        8987
Apple iPhone 7 (A1778)           6326
Apple iPhone Se (A1723)          5187
Apple iPhone 8 (A1905)           4993
Apple iPhone Xr (A2105)          4568
Samsung Galaxy S8 (Sm-G950F)     4520
Apple iPhone X (A1901)           3813
Name: Handset_Type, dtype: int64

In [19]:
#Top 3 handset manufacturers
top_3_handset_manufacturers = user_data['Handset_Manufacturer'].value_counts()[:3]
top_3_handset_manufacturers

Apple      60137
Samsung    40839
Huawei     34423
Name: Handset_Manufacturer, dtype: int64

In [20]:
#Top 5 handsets per top 3 manufactures i.e Apple, Samsung, Huawei
handset_manufacturer_group = user_data.groupby(['Handset_Manufacturer'])

for i in ['Apple', 'Samsung', 'Huawei']:
    print(i)
    print(handset_manufacturer_group.get_group(i)['Handset_Type'].value_counts()[0:5])
    print("")

Apple
Apple iPhone 6S (A1688)    9419
Apple iPhone 6 (A1586)     9023
Apple iPhone 7 (A1778)     6326
Apple iPhone Se (A1723)    5187
Apple iPhone 8 (A1905)     4993
Name: Handset_Type, dtype: int64

Samsung
Samsung Galaxy S8 (Sm-G950F)    4520
Samsung Galaxy A5 Sm-A520F      3724
Samsung Galaxy J5 (Sm-J530)     3696
Samsung Galaxy J3 (Sm-J330)     3484
Samsung Galaxy S7 (Sm-G930X)    3199
Name: Handset_Type, dtype: int64

Huawei
Huawei B528S-23A                  19752
Huawei E5180                       2079
Huawei P20 Lite Huawei Nova 3E     2021
Huawei P20                         1480
Huawei Y6 2018                      997
Name: Handset_Type, dtype: int64

### Recommendation to the marketing Team:

It should target the Apple manufacturers as they have more users in their telecommunication market

Also, they should focus their efforts on the *Huawei B528S-23A* handset type as it has the most
number of engaged users

In [21]:
#Creating a clean csv file before further analysis
user_data.to_csv('../data/clean_data.csv',index=False)

In [22]:
clean_data = pd.read_csv('../data/clean_data.csv')
clean_data

,Bearer_Id,Start,Start_ms,End,End_ms,Dur_ms,IMSI,MSISDN_Number,IMEI,Last_Location_Name,...,Youtube_DL_(Bytes),Youtube_UL_(Bytes),Netflix_DL_(Bytes),Netflix_UL_(Bytes),Gaming_DL_(Bytes),Gaming_UL_(Bytes),Other_DL_(Bytes),Other_UL_(Bytes),Total_UL_(Bytes),Total_DL_(Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,1.585461e+07,2.501332e+06,8.198936e+06,9.656251e+06,2.780823e+08,1.434415e+07,1.717444e+08,8.814393e+06,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,2.024740e+07,1.911173e+07,1.833841e+07,1.722713e+07,6.087501e+08,1.170709e+06,5.269042e+08,1.505514e+07,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,1.972566e+07,1.469958e+07,1.758779e+07,6.163408e+06,2.295846e+08,3.956300e+05,4.106926e+08,4.215763e+06,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,2.138812e+07,1.514664e+07,1.399465e+07,1.097942e+06,7.995382e+08,1.084972e+07,7.490399e+08,1.279728e+07,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,1.525938e+07,1.896287e+07,1.712458e+07,4.152180e+05,5.277072e+08,3.529801e+06,5.507095e+08,1.391032e+07,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,7.277826e+18,4/29/2019 7:28,451.0,4/30/2019 6:02,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,1.619167e+07,1.176343e+07,1.788370e+07,1.967816e+07,5.266097e+08,9.197207e+06,3.264510e+06,1.348742e+07,57628851.0,574175259.0
149997,7.349883e+18,4/29/2019 7:28,483.0,4/30/2019 10:41,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,1.387723e+07,8.288284e+06,1.935015e+07,2.129315e+07,6.268931e+08,4.735033e+06,7.121804e+08,2.457758e+06,39135081.0,666648844.0
149998,1.311448e+19,4/29/2019 7:28,283.0,4/30/2019 10:46,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,2.266051e+07,1.855903e+06,9.963942e+06,5.065760e+06,5.535395e+08,1.339432e+07,1.211009e+08,1.131473e+07,34912224.0,592786405.0
149999,1.311448e+19,4/29/2019 7:28,696.0,4/30/2019 10:40,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8.817106e+06,8.305402e+06,3.322253e+06,1.317259e+07,3.525370e+08,2.529475e+06,8.147131e+08,1.406930e+06,29626096.0,371895920.0
150000,1.013887e+19,4/26/2019 7:25,499.2,4/25/2019 0:01,498.8,104608.6,2.082016e+14,4.188282e+10,4.847455e+13,D41377B,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,41121206.3,454643430.1

In [23]:
'''Aggregate per user using the selected columns as below - Including creating of new rows and 
changing the the display of the data to float of one decimal place
'''


pd.set_option('display.float_format', lambda x: '%.1f' % x)

clean_data['Total_UL_and_DL_(Bytes)'] = clean_data['Total_UL_(Bytes)'] + clean_data['Total_DL_(Bytes)']
clean_data['Other_UL_and_DL_(Bytes)'] = clean_data['Other_UL_(Bytes)'] + clean_data['Other_DL_(Bytes)']
clean_data['Gaming_UL_and_DL_(Bytes)'] = clean_data['Gaming_UL_(Bytes)'] + clean_data['Gaming_DL_(Bytes)']
clean_data['Netflix_UL_and_DL_(Bytes)'] = clean_data['Netflix_UL_(Bytes)'] + clean_data['Netflix_DL_(Bytes)']
clean_data['Youtube_UL_and_DL_(Bytes)'] = clean_data['Youtube_UL_(Bytes)'] + clean_data['Youtube_DL_(Bytes)']
clean_data['Email_UL_and_DL_(Bytes)'] = clean_data['Email_UL(Bytes)'] + clean_data['Email_DL(Bytes)']
clean_data['Google_UL_and_DL_(Bytes)'] = clean_data['Google_UL_(Bytes)'] + clean_data['Google_DL_(Bytes)']
clean_data['Social Media_UL_and_DL_(Bytes)'] = clean_data['Social_Media_UL_(Bytes)'] + clean_data['Social_Media_DL_(Bytes)']
clean_data.head()

,Bearer_Id,Start,Start_ms,End,End_ms,Dur_ms,IMSI,MSISDN_Number,IMEI,Last_Location_Name,...,Total_UL_(Bytes),Total_DL_(Bytes),Total_UL_and_DL_(Bytes),Other_UL_and_DL_(Bytes),Gaming_UL_and_DL_(Bytes),Netflix_UL_and_DL_(Bytes),Youtube_UL_and_DL_(Bytes),Email_UL_and_DL_(Bytes),Google_UL_and_DL_(Bytes),Social Media_UL_and_DL_(Bytes)
0,13114483460844900352.0,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,208201448079117.0,33664962239.0,35521209507511.0,9.16456699548519E+015,...,36749741.0,308879636.0,345629377.0,180558843.0,292426453.0,17855187.0,18355943.0,3701304.0,2905912.0,1570185.0
1,13114483482878900224.0,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,208201909211140.0,33681854413.0,35794009006359.0,L77566A,...,53800391.0,653384965.0,707185356.0,541959383.0,609920783.0,35565545.0,39359124.0,937385.0,4414096.0,1933278.0
2,13114483484080500736.0,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,208200314458056.0,33760627129.0,35281510359387.0,D42335A,...,27883638.0,279807335.0,307690973.0,414908351.0,229980251.0,23751202.0,34425237.0,3363124.0,10229119.0,1726277.0
3,13114483485442799616.0,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,208201402342131.0,33750343200.0,35356610164913.0,T21824A,...,43324218.0,846028530.0,889352748.0,761837216.0,810387875.0,15092588.0,36534765.0,2070983.0,11811761.0,657493.0
4,13114483499480700928.0,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,208201401415120.0,33699795932.0,35407009745539.0,D88865A,...,38542814.0,569138589.0,607681403.0,564619822.0,531237049.0,17539799.0,34222253.0,2110349.0,7748843.0,912788.0

In [24]:
#Selecting a few of the columns for overview analysis of the user behaviour

user_columns = ['Bearer_Id','Dur_ms','MSISDN_Number','Total_UL_and_DL_(Bytes)','Other_UL_and_DL_(Bytes)',
                'Gaming_UL_and_DL_(Bytes)','Netflix_UL_and_DL_(Bytes)','Youtube_UL_and_DL_(Bytes)',
                'Email_UL_and_DL_(Bytes)','Google_UL_and_DL_(Bytes)','Social Media_UL_and_DL_(Bytes)']

user_overview_data = clean_data[user_columns]
user_overview_data.head()

,Bearer_Id,Dur_ms,MSISDN_Number,Total_UL_and_DL_(Bytes),Other_UL_and_DL_(Bytes),Gaming_UL_and_DL_(Bytes),Netflix_UL_and_DL_(Bytes),Youtube_UL_and_DL_(Bytes),Email_UL_and_DL_(Bytes),Google_UL_and_DL_(Bytes),Social Media_UL_and_DL_(Bytes)
0,13114483460844900352.0,1823652.0,33664962239.0,345629377.0,180558843.0,292426453.0,17855187.0,18355943.0,3701304.0,2905912.0,1570185.0
1,13114483482878900224.0,1365104.0,33681854413.0,707185356.0,541959383.0,609920783.0,35565545.0,39359124.0,937385.0,4414096.0,1933278.0
2,13114483484080500736.0,1361762.0,33760627129.0,307690973.0,414908351.0,229980251.0,23751202.0,34425237.0,3363124.0,10229119.0,1726277.0
3,13114483485442799616.0,1321509.0,33750343200.0,889352748.0,761837216.0,810387875.0,15092588.0,36534765.0,2070983.0,11811761.0,657493.0
4,13114483499480700928.0,1089009.0,33699795932.0,607681403.0,564619822.0,531237049.0,17539799.0,34222253.0,2110349.0,7748843.0,912788.0

In [25]:
user_overview_data.to_csv('../data/user_overview_data.csv',index=False)

In [26]:
type(user_overview_data['Total_UL_and_DL_(Bytes)'][0])

numpy.float64

In [27]:
import warnings
warnings.filterwarnings('ignore')

In [28]:
# Converting the data capacity from bytes to Megabytes
for column in user_columns:
    if column not in ['Bearer_Id','Dur_ms','MSISDN_Number']:
        user_overview_data[column]= user_overview_data[column]/(10**6)

user_overview_data.head()

,Bearer_Id,Dur_ms,MSISDN_Number,Total_UL_and_DL_(Bytes),Other_UL_and_DL_(Bytes),Gaming_UL_and_DL_(Bytes),Netflix_UL_and_DL_(Bytes),Youtube_UL_and_DL_(Bytes),Email_UL_and_DL_(Bytes),Google_UL_and_DL_(Bytes),Social Media_UL_and_DL_(Bytes)
0,13114483460844900352.0,1823652.0,33664962239.0,345.6,180.6,292.4,17.9,18.4,3.7,2.9,1.6
1,13114483482878900224.0,1365104.0,33681854413.0,707.2,542.0,609.9,35.6,39.4,0.9,4.4,1.9
2,13114483484080500736.0,1361762.0,33760627129.0,307.7,414.9,230.0,23.8,34.4,3.4,10.2,1.7
3,13114483485442799616.0,1321509.0,33750343200.0,889.4,761.8,810.4,15.1,36.5,2.1,11.8,0.7
4,13114483499480700928.0,1089009.0,33699795932.0,607.7,564.6,531.2,17.5,34.2,2.1,7.7,0.9

In [29]:
#Aggregating all column data about every user
users = user_overview_data.groupby(['MSISDN_Number'])#First group the data by user
users_aggregated = users.agg({'Bearer_Id':'count','Dur_ms':'sum','Total_UL_and_DL_(Bytes)':'sum',
                              'Other_UL_and_DL_(Bytes)':'sum','Gaming_UL_and_DL_(Bytes)':'sum',
                              'Netflix_UL_and_DL_(Bytes)':'sum','Youtube_UL_and_DL_(Bytes)':'sum',
                              'Email_UL_and_DL_(Bytes)':'sum','Google_UL_and_DL_(Bytes)':'sum',
                              'Social Media_UL_and_DL_(Bytes)':'sum'})
users_aggregated

,Bearer_Id,Dur_ms,Total_UL_and_DL_(Bytes),Other_UL_and_DL_(Bytes),Gaming_UL_and_DL_(Bytes),Netflix_UL_and_DL_(Bytes),Youtube_UL_and_DL_(Bytes),Email_UL_and_DL_(Bytes),Google_UL_and_DL_(Bytes),Social Media_UL_and_DL_(Bytes)
MSISDN_Number,,,,,,,,,,
33601001722.0,1,116720.0,878.7,386.6,812.5,27.2,21.6,1.3,4.4,2.2
33601001754.0,1,181230.0,156.9,281.7,119.8,11.2,12.4,3.3,5.3,2.7
33601002511.0,1,134969.0,596.0,501.7,538.8,19.4,21.3,3.2,3.4,3.2
33601007832.0,1,49878.0,422.3,35.3,391.1,1.9,7.0,2.3,9.7,0.3
33601008617.0,2,37104.0,1457.4,804.8,1314.8,49.2,41.5,3.3,18.5,2.9
...,...,...,...,...,...,...,...,...,...,...
33789997247.0,1,140988.0,480.3,211.1,437.0,8.5,19.9,2.5,5.4,0.5
41882819545.0,1066,72551004.6,531744.7,450978.4,461478.0,24253.6,24340.7,2399.9,8248.6,1973.8
3197020876596.0,1,877385.0,232.1,470.5,178.0,26.6,12.0,1.5,10.4,0.7
337000037000919.0,1,253030.0,596.3,149.2,510.1,30.9,36.7,3.3,9.8,0.5
882397108489451.0,1,869844.0,139.2,401.4,43.1,28.8,40.9,3.3,9.2,1.5

In [30]:
'''Describing all relevant variables and associated data types'''
user_overview_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 11 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Bearer_Id                       150001 non-null  float64
 1   Dur_ms                          150001 non-null  float64
 2   MSISDN_Number                   150001 non-null  float64
 3   Total_UL_and_DL_(Bytes)         150001 non-null  float64
 4   Other_UL_and_DL_(Bytes)         150001 non-null  float64
 5   Gaming_UL_and_DL_(Bytes)        150001 non-null  float64
 6   Netflix_UL_and_DL_(Bytes)       150001 non-null  float64
 7   Youtube_UL_and_DL_(Bytes)       150001 non-null  float64
 8   Email_UL_and_DL_(Bytes)         150001 non-null  float64
 9   Google_UL_and_DL_(Bytes)        150001 non-null  float64
 10  Social Media_UL_and_DL_(Bytes)  150001 non-null  float64
dtypes: float64(11)
memory usage: 12.6 MB

Basically, the:

    Bearer_Id Identifies the session that particular call was on
    Dur_ms*Determines the duration of the user's engagement with the telecommunication company
    MSISDN_Number Is the unique customer Identifier (Their mobile number)
    The other variables describe the total data received and sent across those different media for each user

## NON-GRAPHICAL UNIVARIATE ANALYSIS

In [31]:
#Fixing identified outlier
def fix_outlier(df, column):
    df[column] = np.where(df[column] > df[column].quantile(0.95), df[column].median(),df[column])
    
    return df[column]


user_overview_data['Dur_ms']=fix_outlier(user_overview_data,'Dur_ms')
user_overview_data['Total_UL_and_DL_(Bytes)']=fix_outlier(user_overview_data,'Total_UL_and_DL_(Bytes)')
user_overview_data['Other_UL_and_DL_(Bytes)']=fix_outlier(user_overview_data,'Other_UL_and_DL_(Bytes)')
user_overview_data['Gaming_UL_and_DL_(Bytes)']=fix_outlier(user_overview_data,'Gaming_UL_and_DL_(Bytes)')
user_overview_data['Netflix_UL_and_DL_(Bytes)']=fix_outlier(user_overview_data,'Netflix_UL_and_DL_(Bytes)')
user_overview_data['Youtube_UL_and_DL_(Bytes)']=fix_outlier(user_overview_data,'Youtube_UL_and_DL_(Bytes)')
user_overview_data['Email_UL_and_DL_(Bytes)']=fix_outlier(user_overview_data,'Email_UL_and_DL_(Bytes)')
user_overview_data['Google_UL_and_DL_(Bytes)']=fix_outlier(user_overview_data,'Google_UL_and_DL_(Bytes)')
user_overview_data['Social_Media_UL_and_DL_(Bytes)']=fix_outlier(user_overview_data,'Social_Media_UL_and_DL_(Bytes)')

KeyError: 'Social_Media_UL_and_DL_(Bytes)'

In [ ]:
#Analyzing the basic metric for interpretation of their importance for global objectives
user_overview_data.describe()

### Interpretation
The data used in the media have high standard diviation - This clearly explains that users have a high variation in the amount of data sent and received. The data is soo much dispersed with relation to the mean for the majority of the variables

Email data and Social media is however not soo much dispersed hence the majority of the people send and receive almost equal amount of data

Duration of the call is also soo much dispersed

In [ ]:
# Non-graphical univariate analysis of Bearer_Id

users_aggregated['Bearer_Id'].describe()

In [ ]:
# Non-graphical univariate analysis of Dur_ms

users_aggregated['Dur_ms'].describe()

In [ ]:
# Non-graphical univariate analysis of Total_UL_and_DL_(Bytes)

users_aggregated['Total_UL_and_DL_(Bytes)'].describe()

In [ ]:
# Non-graphical univariate analysis of Gaming_UL_and_DL_(Bytes)

users_aggregated['Gaming_UL_and_DL_(Bytes)'].describe()

In [ ]:
# Non-graphical univariate analysis of Netflix_UL_and_DL_(Bytes)

users_aggregated['Netflix_UL_and_DL_(Bytes)'].describe()

In [ ]:
# Non-graphical univariate analysis of Youtube_UL_and_DL_(Bytes)

users_aggregated['Youtube_UL_and_DL_(Bytes)'].describe()

In [ ]:
# Non-graphical univariate analysis of Gaming_UL_and_DL_(Bytes)

users_aggregated['Gaming_UL_and_DL_(Bytes)'].describe()

In [ ]:
# Non-graphical univariate analysis of Email_UL_and_DL_(Bytes)

users_aggregated['Email_UL_and_DL_(Bytes)'].describe()

In [ ]:
# Non-graphical univariate analysis of Google_UL_and_DL_(Bytes)

users_aggregated['Google_UL_and_DL_(Bytes)'].describe()

In [ ]:
###################################PLOTTING FUNCTIONS###################################

def plot_hist(df:pd.DataFrame, column:str, color:str)->None:
    plt.figure(figsize=(15, 10))
    fig, ax = plt.subplots(1, figsize=(12, 7))
    sns.displot(data=df, x=column, color=color, kde=True, height=7, aspect=2)
    plt.title(f'Distribution of {column}', size=20, fontweight='bold')
    plt.show()

def plot_count(df:pd.DataFrame, column:str) -> None:
    plt.figure(figsize=(12, 7))
    sns.countplot(data=df, x=column)
    plt.title(f'Distribution of {column}', size=20, fontweight='bold')
    plt.show()
    
def plot_bar(df:pd.DataFrame, x_col:str, y_col:str, title:str, xlabel:str, ylabel:str)->None:
    plt.figure(figsize=(12, 7))
    sns.barplot(data = df, x=x_col, y=y_col)
    plt.title(title, size=20)
    plt.xticks(rotation=75, fontsize=14)
    plt.yticks( fontsize=14)
    plt.xlabel(xlabel, fontsize=16)
    plt.ylabel(ylabel, fontsize=16)
    plt.show()

def plot_heatmap(df:pd.DataFrame, title:str, cbar=False)->None:
    plt.figure(figsize=(12, 7))
    sns.heatmap(df, annot=True, cmap='viridis', vmin=0, vmax=1, fmt='.2f', linewidths=.7, cbar=cbar )
    plt.title(title, size=18, fontweight='bold')
    plt.show()

def plot_box(df:pd.DataFrame, x_col:str, title:str) -> None:
    plt.figure(figsize=(12, 7))
    sns.boxplot(data = df, x=x_col)
    plt.title(title, size=20)
    plt.xticks(rotation=75, fontsize=14)
    plt.show()

def plot_box_multi(df:pd.DataFrame, x_col:str, y_col:str, title:str) -> None:
    plt.figure(figsize=(12, 7))
    sns.boxplot(data = df, x=x_col, y=y_col)
    plt.title(title, size=20)
    plt.xticks(rotation=75, fontsize=14)
    plt.yticks( fontsize=14)
    plt.show()

def plot_scatter(df: pd.DataFrame, x_col: str, y_col: str, title: str) -> None:
    plt.figure(figsize=(12, 7))
    sns.scatterplot(data = df, x=x_col, y=y_col)
    plt.title(title, size=20)
    plt.xticks(fontsize=14)
    plt.yticks( fontsize=14)
    plt.show()
    
def plot_univariate(df, col1, col2):
    plt.figure(figsize = (20, 15))

    plt.subplot(2, 2, 1)
    plt.hist(df[col1], bins = 20, color = 'green', edgecolor = 'gray', linewidth = 0.5)
    plt.title(f'Histogram of {col1}', size=14)

    plt.subplot(2, 2, 2)
    plt.boxplot(df[col1])
    plt.title(f'Boxplot of {col1}', size=14)

    plt.subplot(2, 2, 3)
    plt.hist(df[col2], bins=20, color='green', edgecolor='gray', linewidth=0.5)
    plt.title(f'Histogram of {col2}', size=14)

    plt.subplot(2, 2, 4)
    plt.boxplot(df[col2])
    plt.title(f'Boxplot of {col2}', size=14)
    
       

    plt.show()

In [ ]:
#Plotting the univariate Graphical Interpretation

plot_univariate(user_overview_data,'Dur_ms','Total_UL_and_DL_(Bytes)')
plot_univariate(user_overview_data,'Other_UL_and_DL_(Bytes)','Gaming_UL_and_DL_(Bytes)')
plot_univariate(user_overview_data,'Netflix_UL_and_DL_(Bytes)','Youtube_UL_and_DL_(Bytes)')
plot_univariate(user_overview_data,'Email_UL_and_DL_(Bytes)','Google_UL_and_DL_(Bytes)')
plot_univariate(user_overview_data,'Gaming_UL_and_DL_(Bytes)')

## Conducting Bivariate Analysis

In [ ]:
#Bivariate analysis of social media data to the total data
plot_scatter(user_overview_data.sample(300), x_col="Social_Media_UL_and_DL_(Bytes)", y_col='Total_UL_and_DL_(Bytes)', title="Total UL_DL vs Social UL_DL")

In [ ]:
#Bivariate analysis of Google_UL_and_D data to the total data
plot_scatter(user_overview_data.sample(300), x_col="Google_UL_and_DL_(Bytes)", y_col='Total_UL_and_DL_(Bytes)', 
             title="Total UL_DL vs 'Google_UL_and_DL_(Bytes)'")

In [ ]:
#Bivariate analysis of Email_UL_and_DL data to the total data
plot_scatter(user_overview_data.sample(300), x_col='Email_UL_and_DL_(Bytes)', y_col='Total_UL_and_DL_(Bytes)', 
             title="Total UL_DL vs Email_UL_and_DL_(Bytes)")

In [ ]:
#Bivariate analysis of Youtube_UL_and_DL to the total data
plot_scatter(user_overview_data.sample(300), x_col="Youtube_UL_and_DL_(Bytes)", y_col='Total_UL_and_DL_(Bytes)', 
             title="Total UL_DL vs Youtube_UL_and_DL_(Bytes)")

In [ ]:
#Bivariate analysis of social media data to the total data
plot_scatter(user_overview_data.sample(300), x_col="Netflix_UL_and_DL_(Bytes)", y_col='Total_UL_and_DL_(Bytes)', 
             title="Total UL_DL vs Netflix_UL_and_DL_(Bytes)")

In [ ]:
#Bivariate analysis of Gaming_UL_and_DL to the total data
plot_scatter(user_overview_data.sample(300), x_col="Gaming_UL_and_DL_(Bytes)", y_col='Total_UL_and_DL_(Bytes)', 
             title="Total UL_DL vs Gaming_UL_and_DL_(Bytes)")

In the game data analysis with respect to the total data, we get to find that an increase in the amount of  data usage linearly results to an increase in the total amount of data. We can therefore predict the total amount of data depending on the gaming data generated

In [ ]:
#Bivariate analysis of Other_UL_and_DL to the total data
plot_scatter(user_overview_data.sample(300), x_col="Other_UL_and_DL_(Bytes)", y_col='Total_UL_and_DL_(Bytes)', 
             title="Total UL_DL vs Other_UL_and_DL_(Bytes))")

In [ ]:
#Correlation of the required columns
correlated_columns = ['Total_UL_and_DL_(Bytes)','Other_UL_and_DL_(Bytes)','Gaming_UL_and_DL_(Bytes)','Netflix_UL_and_DL_(Bytes)','Youtube_UL_and_DL_(Bytes)','Email_UL_and_DL_(Bytes)','Google_UL_and_DL_(Bytes)','Social Media_UL_and_DL_(Bytes)']
sample_data_for_correlation = user_overview_data[correlated_columns]
pd.set_option('display.float_format', lambda x: '%.3f' % x)
correlated = sample_data_for_correlation.corr()
correlated